### ISSUE TITLE
All in One

### ISSUE THREAD

**Issue by vitalikbyrevich** [humansandbag/Valheim-Better-Diving-Mod#4] opened 2023-02-25 11:10 UTC
Good afternoon. Is there no way to put the files inside the mod? As far as I know there is code on the githab that allows to do this for mods that use JTL.

**Comment by humansandbag** [comment] 2023-02-25 16:26
Are you asking about asset loading? If so, I am keeping the assets external from the mod for now and keeping my assets seperate from the assets created by the original mod author. I may embed them in the binary in a future version.

**Comment by vitalikbyrevich** [comment] 2023-03-15 15:51
> Are you asking about asset loading? If so, I am keeping the assets external from the mod for now and keeping my assets seperate from the assets created by the original mod author. I may embed them in the binary in a future version.

Yes, I mean to have the files inside the mod - this is more convenient as it allows you to put the mod in any folder (plugins/folder/folder etc.) rather than just the root (plugins). 
Yesterday when installing on the server I noticed that I can't dive when players are around. The "dive" message appears on the screen, but I can't go deep. Original version of the server from MLIMG works adequately - except for the oxygen bar (there I had to put a large value - so that stamina does not immediately go to zero when near the players)

Translated with www.DeepL.com/Translator (free version)

**Comment by humansandbag** [comment] 2023-03-16 04:21
Thank you for the clarification and thank you for taking the time to report the multi-player diving bugs you encountered. I am aware of both of those bugs and there are already open issues for them. It would help me greatly if you'd check the open issues first before reporting bugs and keep your open issues focused on a single topic in the future. I've added this "All in One" enhancement to the mods roadmap and plan to implement it in a future version.

**Comment by humansandbag** [comment] 2023-04-02 03:07
This enhancement will be included in the next version of the mod.

**Comment by vitalikbyrevich** [comment] 2023-04-02 10:15
> This enhancement will be included in the next version of the mod.

Anyway, I compiled version 1.0.4C1 and the players still can't dive together on the server. I was also told (with version 1.0.3) that the breathing bar goes abruptly to zero and they die - the current one is silent for now.

Saw the new edits now. I will check on the server and report back today

**Comment by vitalikbyrevich** [comment] 2023-04-02 11:02
Checked. Still doesn't work diving when there are players nearby. Mod only works on clients.

**Comment by humansandbag** [comment] 2023-04-04 04:14
Thank you for testing and getting back to me. Please enable the dev console by adding -console to the launch parameters, recreate the issue and attempt to dive, press F5 to open the console and let me know the value of the last_dive_cancel debug value. That will help me track down the cause.

**Comment by vitalikbyrevich** [comment] 2023-04-04 14:48
I'll try the test again, but there didn't seem to be any errors in the logs. What if we use the original mod as a basis? There was no such problem - players could safely dive next to each other. The only problem in it was a sharp drop in the breathing scale - I had to then set the value in the config to 0.1. 

In general today I think I will check your today's fixes in the mod and try to follow the logs.

**Comment by vitalikbyrevich** [comment] 2023-04-04 19:06
[LogOutput.log](https://github.com/humansandbag/Valheim-Better-Diving-Mod/files/11152172/LogOutput.log)
Still can't dive when a player is around. Here's my log file.

**Comment by humansandbag** [comment] 2023-04-05 14:55
The original mod is the source of those issues. Both the dive prevention and rapid oxygen depletion issues are due to the same cause. I am having to make some major changes to the code as the original mod did not appear to take multi-player into account correctly. This caused code on the clients to run for every player conntected to the server rather than just the local player. The logic I added to my fork only brought those issues to the surface. My latest changes will be committed today.

**Comment by vitalikbyrevich** [comment] 2023-04-05 16:16
By the way, I noticed in the config that the type refers to synchronisation with the server, but in the code itself only to "valheim.exe" The server has "valheim_server.exe" file called. So in essence the mod won't work on the server - if I understand correctly. I mean, should I put the mod on the server at all or just keep it on the clients?

**Comment by vitalikbyrevich** [comment] 2023-04-05 16:19
Conflict with Valheim Recycle mod. Log at
[LogOutput.log](https://github.com/humansandbag/Valheim-Better-Diving-Mod/files/11160895/LogOutput.log)
tached. I'll try it without the mod now.

**Comment by humansandbag** [comment] 2023-04-05 16:27
> By the way, I noticed in the config that the type refers to synchronisation with the server, but in the code itself only to "valheim.exe" The server has "valheim_server.exe" file called. So in essence the mod won't work on the server - if I understand correctly. I mean, should I put the mod on the server at all or just keep it on the clients?

The mod will get excluded by the process filter on the server. The client should sync the config from the server however. So you should at least have the config on the server.

**Comment by vitalikbyrevich** [comment] 2023-04-05 16:31
In general without mod (valheim recycle) the same errors. I first thought it was because I had updated the Libs to current versions, but by returning the original ones (from here) - I get the same errors when connecting to the world.

**Comment by humansandbag** [comment] 2023-04-05 16:41
> In general without mod (valheim recycle) the same errors. I first thought it was because I had updated the Libs to current versions, but by returning the original ones (from here) - I get the same errors when connecting to the world.

I will look into those errors. However, it does not appear that they should impact functionality.

**Comment by vitalikbyrevich** [comment] 2023-04-05 16:42
These errors just make it hard to get in) Continuous spawning in the logs and zero fps after about 5 minutes

**Comment by humansandbag** [comment] 2023-04-05 16:48
I understand. I'm attempting to recreate the errors/investigate.

**Comment by humansandbag** [comment] 2023-04-05 18:01
I was able to recreate the errors you were seeing in the log and have commited changes that should resolve them.

**Comment by humansandbag** [comment] 2023-04-07 17:59
I have released a new version of the mod with multiplayer bug fixes. Please test and let me know if the issue persists.

**Comment by humansandbag** [comment] 2023-04-18 02:38
I have confirmed that these issues have been fixed in the latest version.

**Closed as completed by humansandbag** 2023-04-18 02:38 UTC
Labels: enhancement
