### ISSUE TITLE
Immediate Stamina Loss in Multiplayer

### ISSUE THREAD

**Issue by colel18** [humansandbag/Valheim-Better-Diving-Mod#6] opened 2023-03-02 20:52 UTC
I know this has been a known issue for a couple of years now, but I haven't seen any recent updates about it, so I just wanted to ask where it's at. When someone else logs into the server with me and I attempt to dive, I lose all of my stamina almost immediately. Are there any plans to fix this bug? I play exclusively on a dedicated server with a group, so I can only use this mod when nobody else is logged on.

**Comment by humansandbag** [comment] 2023-03-03 14:09
I am looking into this issue. To help me identify the cause, please enable debug mode via the mods config. When the issue happens, press F5 to open the console and take a screenshot of the values and send me the screen shot.

**Comment by colel18** [comment] 2023-03-04 20:39
So I tried replicating this. The behavior still happens, but it's not
consistent. It seems to fix itself sometimes if I log out and log back in
after somebody joins the server. I tried to get the console screenshot, but
for some reason, my console isn't working. I've tried multiple fixes, but
no luck yet. Any other suggestions of how I can get the info to you?

**Comment by humansandbag** [comment] 2023-03-06 15:29
You'll need to enable the console by adding -console as a launch parameter in R2Modman.

**Comment by humansandbag** [comment] 2023-04-02 03:06
I believe I have identified the source of this bug. I am still testing to make sure it has been fixed. I plan to include the bug fix in the next version.

**Comment by colel18** [comment] 2023-04-02 14:40
Awesome, fingers crossed. Sorry I wasn't much help. I still haven't had any
luck getting the console to work properly.

**Comment by humansandbag** [comment] 2023-04-07 17:59
I have released a new version of the mod with multiplayer bug fixes. Please test and let me know if the issue persists.

**Comment by colel18** [comment] 2023-04-08 23:41
Thank you. Unfortunately my group has moved on to other games, but I'll
test as soon as I can convince someone to come back.

**Comment by humansandbag** [comment] 2023-04-09 18:48
Thank you. I am closing this issue. If the issue persists once you test, please feel free to open a new issue.

**Closed as completed by humansandbag** 2023-04-09 18:48 UTC
Labels: bug
