### ISSUE TITLE
Unable to dive after a time

### ISSUE THREAD

**Issue by JohnStickyFingers** [humansandbag/Valheim-Better-Diving-Mod#3] opened 2023-02-19 08:13 UTC
After playing on a world for a bit the player is unable to dive, the time it takes for the dive to stop functioning is inconsistent (it could be immediately upon loading in or after 3 hours). I haven't been able to track down a definitive source for the issue.

My mod list/pack in case it helps. (For r2modman)
[Modlist 01_1676794204432.zip](https://github.com/humansandbag/Valheim-Better-Diving-Mod/files/10776408/Modlist.01_1676794204432.zip)

**Comment by humansandbag** [comment] 2023-02-19 20:08
Thank you. I am investigating this issue. I have added some additional debug values to the mods debug mode that will be useful for identifying the cause. Those new debug values will be included in version 1.0.3. I plan to release it sometime this week.

**Comment by humansandbag** [comment] 2023-02-25 05:50
I have released v1.0.3. If the issue occurs again, enable debug mode in the config and enable the Vahleim console. Recreate the issue and attempt to dive, press F5 to open the console and let me know the value of the last_dive_cancel debug value. That will help me track down the cause.

**Comment by humansandbag** [comment] 2023-02-26 06:14
Is this issue still occurring with the latest version?

**Comment by humansandbag** [comment] 2023-04-02 03:05
I believe I have identified the source of this bug. I am still testing to make sure it has been fixed. I plan to include the bug fix in the next version.

**Comment by humansandbag** [comment] 2023-04-07 17:59
I have released a new version of the mod with multiplayer bug fixes. Please test and let me know if the issue persists.

**Comment by humansandbag** [comment] 2023-04-18 02:38
I have confirmed that these issues have been fixed in the latest version.

**Closed as completed by humansandbag** 2023-04-18 02:38 UTC
Labels: bug
